{{- if .Values.ingress.enabled -}}
{{- $fullName := include "web-app.fullname" . -}}
{{- $svcPort := .Values.ingress.servicePort -}}
{{- if semverCompare ">=1.14-0" .Capabilities.KubeVersion.GitVersion -}}
apiVersion: networking.k8s.io/v1beta1
{{- else -}}
apiVersion: extensions/v1beta1
{{- end }}
kind: Ingress
metadata:
  name: {{ $fullName }}
  labels:
    {{- include "web-app.labels" . | nindent 4 }}
  {{- with .Values.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- if .Values.ingress.tlsEnabled }}
  tls:
    - hosts:
        {{- range .Values.ingress.hosts }}
        - {{ tpl .host $ | quote }}
        {{- end }}
      {{- if .Values.ingress.tlsSecretName }}
      secretName: {{ .Values.ingress.tlsSecretName }}
      {{- else }}
      secretName: {{ $fullName }}-tsl
      {{- end }}
  {{- end }}
  rules:
    {{- range .Values.ingress.hosts }}
    - host: {{ tpl .host $ | quote }}
      http:
        paths:
          {{- range .paths }}
          {{- if kindIs "string" . }}
          - path: {{ tpl . $ }}
            backend:
              serviceName: {{ $fullName }}
              servicePort: {{ $svcPort }}
          {{- else }}
          - path: {{ tpl .path $ }}
            {{- if .backend }}
            backend:
              serviceName: {{ default $fullName ( tpl .backend.serviceName $ ) }}
              servicePort: {{ default $svcPort ( tpl .backend.servicePort $ ) }}
            {{- else }}
              serviceName: {{ $fullName }}
              servicePort: {{ $svcPort }}
            {{- end }}
          {{- end }}
          {{- end }}
    {{- end }}
  {{- end }}
